---
title: "SKMM2 DGE dRNAsub 2"
author: "Rebecca L"
date: "2024-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(pheatmap)
library(DESeq2)
library(kableExtra)
library(vsn)
library(ggfortify)
library(PCAtools)
library(AnnotationDbi)
library (org.Hs.eg.db)
library(PCAtools)
library(reshape2)
library(RColorBrewer)
library(fgsea)
library(GOSemSim)
library(enrichplot)
library(clusterProfiler)
library(ggvenn)
library(gplots)
library(purrr)
source("customfunc.R")
```

```{r import and normalisation}

#Count matrix
readcounts=read.table("drnasub_SKMM2_counts_gene.txt", row.names=1, header=T, sep="\t")
readcounts$ensembl=rownames(readcounts)

#Annotate HGNC symbols
gene_info=read.csv("tx_v46_info.csv", header=TRUE)[,c(2:3)]
readcounts_an=left_join(readcounts, gene_info, by=join_by(ensembl==GENENAME), multiple="any")
rownames(readcounts_an)=readcounts_an$ensembl
#Sample Information
sampleinfo=read.table("sampleinfo.csv", header=T, row.names=1, sep=",")[7:12,]
sampleinfo$Condition=as.factor(sampleinfo$Condition)

#Filter out 'IG' genes
ig=grep('^IGH|^IGK|^IGL|^HLA', readcounts_an$HGNC)
readcounts_an=readcounts_an[-ig,]

#Make DESeq Dataset & Filter No Counts
readcounts_an[,1:6]=sapply(readcounts_an[1:6], as.integer)
dds=DESeqDataSetFromMatrix(countData=readcounts_an[,1:6], 
                           colData=sampleinfo, 
                           design=~Condition)

hgnc=readcounts_an$HGNC
mcols(dds)= DataFrame(mcols(dds), hgnc)
mcols(dds)

#DESeq Object
dds <- estimateSizeFactors(dds)
dds=dds[rowSums(counts(dds))>=1,]

#DESeq + VSD Normalisation
dds=DESeq(dds)
vsd=vst(dds, blind=FALSE)
vsd_mat=as.matrix(assay(vsd))
meanSdPlot(vsd_mat, ranks=FALSE)

```

```{r DGE}

#Extract results for each contrast into df
my.contrasts=resultsNames(dds)[2]

result_list <- list()
for (i in my.contrasts)
  { res <- results(dds, name=i, alpha=0.05)
  result_list[i] <- res
}

df_list=lapply(result_list, as.data.frame)
df_list=lapply(df_list, mutate,hgnc=dds@rowRanges@elementMetadata$hgnc)
lapply(result_list, head)
lapply(result_list, DESeq2::summary)

#Annotate significance

df_list=lapply(df_list,mutate, sig=case_when(padj<0.05 &log2FoldChange>1 ~"UP", padj<0.05 &log2FoldChange< -1~"DOWN", .default="NS"))

volcano.colours=c(DOWN="blue",NS="black",UP="red")


#Volcano Plots
ggplot(df_list$Condition_IL6_vs_Control, aes(x=log2FoldChange, y=-log10(padj), colour=sig))+
  geom_point()+ 
  scale_colour_manual(values=volcano.colours)+
  geom_hline(yintercept=-log10(0.05), colour="grey30", linetype="dashed") +
  scale_y_continuous(limits=c(0, 25))+
  scale_x_continuous(limits=c(-10,10))+ theme(
    legend.text = element_text(size =14),
    axis.text = element_text(size = 18), 
    axis.title.x=element_text(size=18),
    axis.title.y=element_text(size=18)
  )

#Export results
write.csv(df_list$Condition_IL6_vs_Control,"DGE_drnasub.csv")
```


---
title: "SKMM2 DGE dRNAsub 2"
author: "Rebecca L"
date: "2024-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(pheatmap)
library(DESeq2)
library(kableExtra)
library(vsn)
library(ggfortify)
library(PCAtools)
library(AnnotationDbi)
library (org.Hs.eg.db)
library(PCAtools)
library(reshape2)
library(RColorBrewer)
library(fgsea)
library(GOSemSim)
library(enrichplot)
library(clusterProfiler)
library(ggvenn)
library(gplots)
library(purrr)
library(ggrepel)  # For gene label positioning
source("customfunc.R")
```

```{r import and normalisation}
#Count matrix
readcounts=read.table("drnasub_SKMM2_counts_gene.txt", row.names=1, header=T, sep="\t")
readcounts$ensembl=rownames(readcounts)

#Annotate HGNC symbols
gene_info=read.csv("tx_v46_info.csv", header=TRUE)[,c(2:3)]
readcounts_an=left_join(readcounts, gene_info, by=join_by(ensembl==GENENAME), multiple="any")
rownames(readcounts_an)=readcounts_an$ensembl

#Sample Information
sampleinfo=read.table("sampleinfo.csv", header=T, row.names=1, sep=",")[7:12,]
sampleinfo$Condition=as.factor(sampleinfo$Condition)

#Filter out 'IG' genes
ig=grep('^IGH|^IGK|^IGL|^HLA', readcounts_an$HGNC)
readcounts_an=readcounts_an[-ig,]

#Make DESeq Dataset & Filter No Counts
readcounts_an[,1:6]=sapply(readcounts_an[1:6], as.integer)
dds=DESeqDataSetFromMatrix(countData=readcounts_an[,1:6], 
                           colData=sampleinfo, 
                           design=~Condition)
hgnc=readcounts_an$HGNC
mcols(dds)= DataFrame(mcols(dds), hgnc)
mcols(dds)

#DESeq Object
dds <- estimateSizeFactors(dds)
dds=dds[rowSums(counts(dds))>=1,]

#DESeq + VSD Normalisation
dds=DESeq(dds)
vsd=vst(dds, blind=FALSE)
vsd_mat=as.matrix(assay(vsd))
meanSdPlot(vsd_mat, ranks=FALSE)
```

```{r DGE}
#Extract results for each contrast into df
my.contrasts=resultsNames(dds)[2]
result_list <- list()
for (i in my.contrasts)
  { res <- results(dds, name=i, alpha=0.05)
  result_list[i] <- res
}
df_list=lapply(result_list, as.data.frame)
df_list=lapply(df_list, mutate,hgnc=dds@rowRanges@elementMetadata$hgnc)
lapply(result_list, head)
lapply(result_list, DESeq2::summary)

#Annotate significance with more refined categories
df_list=lapply(df_list, mutate, 
               sig=case_when(
                 padj < 0.05 & log2FoldChange > 1 ~ "Upregulated",
                 padj < 0.05 & log2FoldChange < -1 ~ "Downregulated", 
                 padj < 0.05 & abs(log2FoldChange) <= 1 ~ "Significant",
                 .default = "Not significant"
               ))

# Publication-ready volcano plot
volcano_data <- df_list$Condition_IL6_vs_Control

# Define colors for publication
volcano.colours <- c(
  "Upregulated" = "#E31A1C",      # Red
  "Downregulated" = "#1F78B4",    # Blue  
  "Significant" = "#33A02C",      # Green
  "Not significant" = "#636363"   # Gray
)

# Create publication-quality volcano plot
volcano_plot <- ggplot(volcano_data, aes(x = log2FoldChange, y = -log10(padj), color = sig)) +
  geom_point(size = 0.8, alpha = 0.7) + 
  scale_color_manual(values = volcano.colours,
                     name = "",
                     breaks = c("Upregulated", "Downregulated", "Significant", "Not significant")) +
  
  # Add significance thresholds
  geom_hline(yintercept = -log10(0.05), color = "black", linetype = "dashed", linewidth = 0.5) +
  geom_vline(xintercept = c(-1, 1), color = "black", linetype = "dashed", linewidth = 0.5) +
  
  # Set axis limits and breaks
  scale_y_continuous(
    limits = c(0, 25),
    breaks = seq(0, 25, 5),
    expand = c(0.02, 0)
  ) +
  scale_x_continuous(
    limits = c(-10, 10),
    breaks = seq(-10, 10, 2),
    expand = c(0.02, 0)
  ) +
  
  # Labels
  labs(
    x = expression("log"[2]*" fold change"),
    y = expression("-log"[10]*" adjusted P-value")
  ) +
  
  # Publication theme
  theme_classic() +
  theme(
    axis.text = element_text(size = 8, color = "black"),
    axis.title = element_text(size = 9, color = "black"),
    legend.text = element_text(size = 8, color = "black"),
    legend.position = "top",
    legend.justification = "center",
    legend.margin = margin(0, 0, 10, 0),
    axis.line = element_line(color = "black", linewidth = 0.5),
    axis.ticks = element_line(color = "black", linewidth = 0.5),
    axis.ticks.length = unit(2, "pt"),
    plot.margin = margin(10, 10, 10, 10),
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA),
    legend.key = element_blank()
  ) +
  
  # Add count annotations
  annotate("text", x = 8, y = 23, 
           label = paste0("Up: ", sum(volcano_data$sig == "Upregulated", na.rm = TRUE)),
           size = 2.5, color = "#E31A1C") +
  annotate("text", x = -8, y = 23, 
           label = paste0("Down: ", sum(volcano_data$sig == "Downregulated", na.rm = TRUE)),
           size = 2.5, color = "#1F78B4")

# Save as publication-ready PDF
ggsave("volcano_plot_publication.pdf", volcano_plot, 
       width = 4, height = 4.5, units = "in", dpi = 300)

# Optional: Add gene labels for top significant genes
# Identify top genes to label (most significant up and down)
top_genes <- volcano_data %>%
  filter(sig %in% c("Upregulated", "Downregulated")) %>%
  arrange(padj) %>%
  head(10)

# Volcano plot with gene labels
volcano_plot_labeled <- volcano_plot +
  geom_text_repel(
    data = top_genes,
    aes(label = hgnc),
    size = 2.5,
    color = "black",
    max.overlaps = 10,
    box.padding = 0.3,
    point.padding = 0.3,
    segment.size = 0.3,
    segment.color = "black",
    show.legend = FALSE
  )

# Save labeled version
ggsave("volcano_plot_with_labels.pdf", volcano_plot_labeled, 
       width = 4.5, height = 4.5, units = "in", dpi = 300)

#Export results
write.csv(df_list$Condition_IL6_vs_Control,"DGE_drnasub.csv")
```





