---
title: "skmm2"
output: html_document
date: "2025-08-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

my_lib_path <- c("/ceph/project/otmc/asriniva/R/x86_64-pc-linux-gnu-library/4.5", "/ceph/project/otmc/asriniva/R/x86_64-pc-linux-gnu-library/4.4")
.libPaths(c(my_lib_path, .libPaths()))

my_lib_path <- c("/ceph/project/otmc/asriniva/R/x86_64-pc-linux-gnu-library/4.5")

if (! my_lib_path[1] %in% .libPaths()) {
  .libPaths(c(my_lib_path[1], .libPaths()))
}

Sys.setenv("R_LIBS_USER" = my_lib_path[1])  # necessary for RStudio

.libPaths()
Sys.setenv("R_LIBS_USER" = .libPaths()[4])  # necessary for RStudio


#BiocManager::install(c("BSgenome.Hsapiens.NCBI.GRCh38"))
library(tidyverse)
library(data.table)
library(reshape2)
library(this.path)
library(ggpubr)

library(DESeq2)
library(apeglm)
library(EnhancedVolcano)
library(UpSetR)
library(VennDiagram)
library(DEXSeq)
library(DRIMSeq)
#BiocManager::install(c("stageR"))

library(stageR)
library(bambu)
#library(bambu, lib.loc = "/ceph-fast/package/u22/R-cbrg/current/4.5.1")

library(pheatmap)
library(BSgenome.Hsapiens.NCBI.GRCh38)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(GenomeInfoDb, lib.loc = "/ceph-fast/package/u22/R-cbrg/current/4.5.2")
#library(ggbio)
library(rtracklayer)
#BiocManager::install(c("AnnotationHub"))
library(AnnotationHub)
library(ensembldb)
library(AnnotationDbi)


#devtools::install_github("dzhang32/ggtranscript")

library(ggtranscript)


# Load AnnotationHub

setwd(this.path::this.dir())

setAnnotationHubOption("CACHE", "/ceph/project/otmc/asriniva/.cache/R/AnnotationHub")
ah <- AnnotationHub()

# Find EnsDb for Ensembl 104 (human)
query(ah, c("EnsDb", "104", "Homo sapiens"))  # List available databases
query(ah, c("EnsDb", "86", "Homo sapiens"))  # List available databases
query(ah, c("gencode", "Homo"))

# Retrieve EnsDb for Ensembl 104
edb <- ah[["AH95744"]]  # Change ID if needed (check output of query())

conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("select", "dplyr")
conflicted::conflicts_prefer(ggplot2::ggsave)
conflicted::conflicts_prefer(base::as.factor)
conflicted::conflicts_prefer(SummarizedExperiment::rowRanges)
```


```{r load_bambu_data}
##Bambu run as batch script due to Memory requirement
load("bambu_SKMM_all2_new.RData")
se.bambu_46_SKMM_full <- readRDS("se.bambu_46_SKMM_all2_new.RDS")

plots_dir <- "plots"
dir.create(plots_dir, showWarnings = F)


#se.bambu_46_SKMM_full@assays
#assay(se.bambu_46_SKMM_full)

bambu::writeBambuOutput(se.bambu_46_SKMM_full, "bambu_SKMM_all_res_new")

  
```


```{r PCA, fig.height=5}
se.bambu <- se.bambu_46_SKMM_full
dim(se.bambu)

samples <- c(
  "SKMM2control1_gene.sorted",
  "SKMM2control2_gene.sorted",
  "SKMM2control3_gene.sorted",
  "SKMM2IL61_gene.sorted",
  "SKMM2IL62_gene.sorted",
  "SKMM2IL63_gene.sorted",
  "sub_SKMM2_drna_control1_gene.sorted",
  "sub_SKMM2_drna_control2_gene.sorted",
  "sub_SKMM2_drna_control3_gene.sorted",
  "sub_SKMM2_drna_IL61_gene.sorted",
  "sub_SKMM2_drna_IL62_gene.sorted",
  "sub_SKMM2_drna_IL63_gene.sorted"
)

renamed_samples <- c(
  "SKMM2_cDNA_control_1",
  "SKMM2_cDNA_control_2",
  "SKMM2_cDNA_control_3",
  "SKMM2_cDNA_IL6_1",
  "SKMM2_cDNA_IL6_2",
  "SKMM2_cDNA_IL6_3",
  "SKMM2_dRNA_control_1",
  "SKMM2_dRNA_control_2",
  "SKMM2_dRNA_control_3",
  "SKMM2_dRNA_IL6_1",
  "SKMM2_dRNA_IL6_2",
  "SKMM2_dRNA_IL6_3"
)

sampleinfo <- data.frame(sample=samples, name=renamed_samples) %>%
  mutate(
    method = ifelse(str_detect(name, "dRNA"), "dRNA", "cDNA"),
    condition = ifelse(str_detect(name, "IL6"), "IL6", "Control")
  ) %>%
  mutate(method = as.factor(method), condition = as.factor(condition)) %>%
  mutate(group = paste(method, condition, sep=" ") %>% as.factor())

colnames(se.bambu) <- renamed_samples
rownames(sampleinfo) <- renamed_samples
colData(se.bambu) <- DataFrame(sampleinfo)
#rownames(se.bambu) <- tools::file_path_sans_ext(rownames(se.bambu))
#rownames(se.bambu)

colData(se.bambu)

PCA <- plotBambu(se.bambu, type = "pca", group.variable = c("group")) %>% 
  ggpubr::ggpar(legend = "bottom", 
                #legend.title = "SKMM2", 
                legend.title = "", 
                title="PCA of transcript expression in SKMM2, all transcripts", font.title = c(10))

PCA_novel <- bambu::plotBambu(se.bambu[str_detect(rownames(se.bambu), "^Bambu")], type = "pca", group.variable = c("group")) %>% 
  ggpubr::ggpar(legend = "bottom", 
                #legend.title = "SKMM2", 
                legend.title="",
                title="PCA of transcript expression in SKMM2, novel transcripts", 
                font.title = c(10))


PCA
ggsave(file.path(plots_dir, "PCA_transcript.svg"), height = 3, width = 3, units = "in", dpi = 300, bg="white")



PCA_novel
ggsave(file.path(plots_dir, "PCA_novel_transcript.svg"), height = 3, width = 3, units = "in", dpi = 300, bg="white")


seGene.multiSample <- transcriptToGeneExpression(se.bambu)
bambu_gene_counts_to_df <- seGene.multiSample %>% 
  assay() %>% as.data.frame()

bambu_gene_counts_to_df["ENSG00000186153.18", ]

saveRDS(seGene.multiSample, "seGene.multiSample.SKMM2_all.46.RDS")

write.table(bambu_gene_counts_to_df, 
            file = "bambu_gene_counts_SKMM_all_46.tsv", 
            sep = "\t", quote = FALSE, col.names = NA)




```

```{r setup_deseq2}
prepped_coldata <- sampleinfo

prepped_counts_genes <- 
  assays(seGene.multiSample)$counts[, prepped_coldata$name] %>%
  round()


##setup deseq params
deseq2_design_condition <- "condition"
control <- "Control"
test <- "IL6"
formula_str <- paste0("~ method + ", deseq2_design_condition) # Change here
design_formula <- as.formula(formula_str)

## run deseq with batch correction
dds <- DESeqDataSetFromMatrix(prepped_counts_genes, 
                              colData = prepped_coldata,
                              design = design_formula) # correct for BATCH

dds$condition <- relevel(dds$condition, ref = control)

## filter for expressed genes.

keep <- rowSums(assay(dds) >= 10) >=
  round((nrow(colData(dds))/4))

dds <- dds[keep,]

dds.deseq <- DESeq(dds)


res_Control_vs_IL6 <- 
  DESeq2::results(dds.deseq, contrast = c(deseq2_design_condition, test, control))

res_cDNA_vs_dRNA <- 
  DESeq2::results(dds.deseq, contrast = c("method", "dRNA", "cDNA"))


contrast_list <- DESeq2::resultsNames(dds.deseq)
contrast_list
contrasts <- contrast_list[str_which(contrast_list, test)]

```

```{r novel_genes}
Novel_transcript_control <- 
  se.bambu %>% assay() %>% 
  round() %>%
  as.data.frame() %>% 
  rownames_to_column("transcript") %>% 
  filter(transcript %>% str_detect("Bambu")) %>% 
  select(transcript, sampleinfo %>% filter(condition=="Control") %>% pull(name)) %>%
  mutate(num_samples_expr = rowSums(across(-transcript, ~ .x >= 5))) %>%
  filter(num_samples_expr >= 3) %>%
  select(-num_samples_expr)

Novel_gene_control <- 
  seGene.multiSample %>% assay() %>% 
  round() %>%
  as.data.frame() %>% 
  rownames_to_column("gene") %>% 
  filter(gene %>% str_detect("Bambu")) %>% 
  select(gene, sampleinfo %>% filter(condition=="Control") %>% pull(name)) %>%
  mutate(num_samples_expr = rowSums(across(-gene, ~ .x >= 5))) %>%
  filter(num_samples_expr >= 3) %>%
  select(-num_samples_expr)
```

```{r review_novel_genes}
library(GenomicRanges)
library(dplyr)

# Extract key columns from rowRanges(se.bambu)
tx_annot_all <- as.data.frame(rowRanges(se.bambu)) %>%
  select(TXID=group_name, seqnames, start, end, width, strand) %>%
  mutate(txClassDescription = ifelse(str_detect(TXID, "Bambu"), "novel", "known"))

# Keep only novel transcripts
tx_annot <- tx_annot_all %>% filter(grepl("^Bambu", TXID) | txClassDescription != "known")

rd <- as.data.frame(rowData(se.bambu)) %>%
  select(TXNAME, GENEID)  # TXNAME should match rownames of rowRanges

# Join on transcript name
tx_annot <- tx_annot %>%
  left_join(rd, by = c("TXID" = "TXNAME"))

# Optional: keep only columns needed
tx_annot <- tx_annot %>%
  select(TXID, GENEID, seqnames, start, end, width, strand, txClassDescription)



gene_annot <- as.data.frame(rowRanges(seGene.multiSample)) %>%
  select(GENEID=group_name, seqnames, start, end, strand, width)


# Make GRanges objects
tx_gr <- GRanges(seqnames = tx_annot$seqnames,
                 ranges = IRanges(start = tx_annot$start, end = tx_annot$end),
                 strand = tx_annot$strand,
                 txname = tx_annot$TXID,
                 geneid = tx_annot$GENEID)

known_gr <- gtf_annotation[gtf_annotation$type == "gene"]

# Find overlaps (same strand)
ov <- findOverlaps(tx_gr, known_gr, ignore.strand = FALSE)
tx_annot$overlaps_known <- FALSE
tx_annot$overlaps_known[queryHits(ov)] <- TRUE


tx_summary <- tx_annot %>%
  group_by(GENEID) %>%
  summarise(
    n_transcripts = n(),
    min_width = min(width),
    overlaps_known_any = any(overlaps_known)
  ) %>%
  mutate(likely_real = (n_transcripts >= 2) & (min_width >= 200) & (!overlaps_known_any))


probable_novel_genes <-
  tx_summary %>%
  filter(likely_real) %>%
  pull(GENEID)
```

```{r gtf}
bambu_gtf <- 
  import("bambu_SKMM_all_res/extended_annotations.gtf")

annotation_table <- import(gtf_file) %>% as.data.frame()
tx_annot_df <- annotation_table %>%
  filter(type == "transcript") %>%
  select(gene_id, gene_name, gene_type, transcript_id) %>%
  distinct()

gene_annot_df <- tx_annot_df %>% 
    select(gene_id, gene_name, gene_type) %>%
  distinct()
```

```{r setup_mini_se}
assay(se.bambu) <- assay(se.bambu) %>% round()

# Control only: method comparison
se.control <- se.bambu[, colData(se.bambu)$condition == "Control"]

# IL6 only: method comparison
se.il6 <- se.bambu[, colData(se.bambu)$condition == "IL6"]

# cDNA only: condition comparison
se.cdna <- se.bambu[, colData(se.bambu)$method == "cDNA"]

# dRNA only: condition comparison
se.drna <- se.bambu[, colData(se.bambu)$method == "dRNA"]


```

```{r deseq_dte}
run_DESeq2_wrapper <- function(se_subset,
                               design_formula,
                               contrast_vec,
                               lfcshrink = TRUE,
                               shrink_type = c("apeglm","normal"),
                               vst_blind = FALSE,
                               countsAssay = "counts",
                               min_count = 5, min_samples = 3) {

  library(DESeq2)
  shrink_type <- match.arg(shrink_type)

  ## --- filter ---
  keep <- rowSums(assay(se_subset, countsAssay) >= min_count) >= min_samples
  se_sub_filt <- se_subset[keep, ]

  ## --- DESeq2 ---
  dds <- DESeqDataSet(se_sub_filt, design = design_formula)
  dds <- DESeq(dds, quiet = TRUE)

  ## --- VST ---
  vsd <- vst(dds, blind = vst_blind)

  ## --- results ---
  res_raw <- DESeq2::results(dds, contrast = contrast_vec, alpha = 0.05)
  res_raw_df <- as.data.frame(res_raw)
  res_raw_df$feature <- rownames(res_raw_df)

  ## add annotation from rowData
  rd <- as.data.frame(rowData(se_sub_filt))
  rd$feature <- rownames(rd)
  res_raw_df <- dplyr::left_join(res_raw_df, rd, by = "feature")

  ## --- LFC shrink ---
  res_shr_df <- NULL
  if (lfcshrink) {
    if (shrink_type == "apeglm" && requireNamespace("apeglm", quietly = TRUE)) {
      res_shr <- tryCatch({
        lfcShrink(dds, contrast = contrast_vec, type = "apeglm")
      }, error = function(e) {
        message("apeglm shrink failed: ", e$message, " -> falling back to normal.")
        lfcShrink(dds, contrast = contrast_vec, type = "normal")
      })
    } else {
      res_shr <- lfcShrink(dds, contrast = contrast_vec, type = "normal")
    }
    res_shr_df <- as.data.frame(res_shr)
    res_shr_df$feature <- rownames(res_shr_df)
    res_shr_df <- dplyr::left_join(res_shr_df, rd, by = "feature")
  }

  return(list(dds = dds,
              vsd = vsd,
              res_raw = res_raw_df,
              res_shr = res_shr_df))
}

```

```{r plots_dte}
plot_DESeq2_results <- function(deseq_out,
                                intgroups = c("method","condition"),
                                top_n = 50,
                                prefix = "comparison",
                                outdir = "results",
                                novel_only = TRUE) {

  library(ggplot2)
  library(pheatmap)

  if (!dir.exists(outdir)) dir.create(outdir, recursive = TRUE)

  ## --- choose table (shrunk preferred) ---
  res_df <- if (!is.null(deseq_out$res_shr)) deseq_out$res_shr else deseq_out$res_raw

  ## --- filter to novel transcripts/genes ---
  if (novel_only) {
    res_df <- res_df[
      (res_df$novelTranscript %in% TRUE) | grepl("^Bambu", res_df$TXNAME) |
      (res_df$novelGene %in% TRUE)       | grepl("^Bambu", res_df$GENEID), 
      ]
    
  }
  
  # Drop list columns before writing results
  clean_df <- res_df[, !sapply(res_df, is.list), drop = FALSE]

  ## --- save results ---
  write.csv(clean_df, file.path(outdir, paste0(prefix, "_DE_results.csv")), row.names = FALSE)

  ## --- PCA plot ---
  pca_data <- plotPCA(deseq_out$vsd, intgroup = intgroups, returnData = TRUE)
  percentVar <- round(100 * attr(pca_data, "percentVar"))
  p_pca <- ggplot(pca_data, aes(PC1, PC2, color = !!sym(intgroups[1]), shape = !!sym(intgroups[2]))) +
    geom_point(size = 3) +
    xlab(paste0("PC1: ", percentVar[1], "% variance")) +
    ylab(paste0("PC2: ", percentVar[2], "% variance")) +
    ggtitle(paste0("PCA: ", prefix))
  ggsave(file.path(outdir, paste0(prefix, "_PCA.png")), p_pca, width = 6, height = 5)

  ## --- MA plot ---
  p_ma <- ggplot(res_df, aes(x = log10(baseMean + 1), y = log2FoldChange)) +
    geom_point(alpha = 0.4, size = 0.7) +
    geom_hline(yintercept = 0, color = "blue", linetype = "dashed") +
    xlab("log10(baseMean + 1)") + ylab("log2FC") +
    ggtitle(paste0("MA plot (novel only): ", prefix))
  ggsave(file.path(outdir, paste0(prefix, "_MA.png")), p_ma, width = 6, height = 5)

  ## --- Heatmap ---
  mat <- assay(deseq_out$vsd)
  if (nrow(res_df) > 0) {
    sig_feats <- head(res_df$feature[order(res_df$pvalue)], n = min(top_n, nrow(res_df)))
    mat_sel <- mat[sig_feats, , drop = FALSE]
    mat_sel <- mat_sel - rowMeans(mat_sel)
    anno <- as.data.frame(colData(deseq_out$dds)[, intgroups, drop = FALSE])
    pheatmap(mat_sel, annotation_col = anno,
             show_rownames = FALSE,
             main = paste0("Top ", top_n, " novel DE: ", prefix),
             filename = file.path(outdir, paste0(prefix, "_heatmap.png")))
  }

  return(list(results = res_df, pca_plot = p_pca, ma_plot = p_ma))
}

```


```{r cdna}
# IL6 vs Control in cDNA only
out_cdna <- run_DESeq2_wrapper(se.cdna,
                               design_formula = ~ condition,
                               contrast_vec = c("condition","Control","IL6"),
                               vst_blind = FALSE)



plots_cdna <- plot_DESeq2_results(out_cdna,
                                  intgroups = c("condition", "method"),
                                  prefix = "cDNA_IL6_vs_Control",
                                  outdir = "DE_novel")


result_dte_cdna <- plots_cdna$results %>% 
  filter(padj < 0.05) %>%
  filter(GENEID %in% probable_novel_genes | str_detect(GENEID, "^ENSG") )


```


```{r drna}
# IL6 vs Control in dRNA only
out_drna <- run_DESeq2_wrapper(se.drna,
                               design_formula = ~ condition,
                               contrast_vec = c("condition","Control","IL6"),
                               vst_blind = FALSE)



plots_drna <- plot_DESeq2_results(out_drna,
                                  intgroups = c("condition", "method"),
                                  prefix = "dRNA_IL6_vs_Control",
                                  outdir = "DE_novel")


result_dte_drna <- plots_drna$results %>% 
  filter(padj < 0.05) %>%
  filter(GENEID %in% probable_novel_genes | str_detect(GENEID, "^ENSG") )


result_dte_drna %>%
  filter(TXNAME %in% result_dte_cdna$TXNAME)


result_dte_cdna %>%
  filter(TXNAME %in% result_dte_drna$TXNAME)
```


```{r control}
# dRNA vs cDNA in Control only
out_control <- run_DESeq2_wrapper(se.control,
                               design_formula = ~ method,
                               contrast_vec = c("method","cDNA","dRNA"),
                               vst_blind = FALSE)



plots_control <- plot_DESeq2_results(out_control,
                                  intgroups = c("condition", "method"),
                                  prefix = "Control_dRNA_vs_cDNA",
                                  outdir = "DE_novel")


result_dte_control <- plots_control$results %>% 
  filter(padj < 0.05) %>%
  filter(GENEID %in% probable_novel_genes | str_detect(GENEID, "^ENSG") )
```


```{r IL6}
# dRNA vs cDNA in IL6 only
out_il6 <- run_DESeq2_wrapper(se.il6,
                               design_formula = ~ method,
                               contrast_vec = c("method","cDNA","dRNA"),
                               vst_blind = FALSE)



plots_il6 <- plot_DESeq2_results(out_il6,
                                  intgroups = c("condition", "method"),
                                  prefix = "Control_dRNA_vs_cDNA",
                                  outdir = "DE_novel")



result_dte_il6 <- plots_il6$results %>% 
  filter(padj < 0.05) %>%
  filter(GENEID %in% probable_novel_genes | str_detect(GENEID, "^ENSG") )



result_dte_il6 %>%
  filter(TXNAME %in% result_dte_control$TXNAME)


result_dte_control %>%
  filter(TXNAME %in% result_dte_il6$TXNAME)


```


```{r additional_plots}
library(ggplot2)
library(EnhancedVolcano)
library(pheatmap)
library(dplyr)
annotate_and_plot <- function(res_df, tx_annot_df, vsd=NULL,prefix,
                              padj_cutoff = 0.05, 
                              lfc_cutoff = 1, 
                              top_n = 25,
                              heatmap_breaks,
                              novel_only = TRUE) {
  # ---- Step 1: Annotate ----
  res_annot <- res_df %>%
    filter(GENEID %in% probable_novel_genes | str_detect(GENEID, "^ENSG") ) %>%
    left_join(tx_annot_df, by = c("GENEID" = "gene_id")) %>%
    mutate(gene_name = ifelse(is.na(gene_name), "NovelGene", gene_name)) %>%
    mutate(display_id = paste(gene_name, TXNAME, sep = "_"))
  
  if (novel_only) {
    res_annot <- res_annot %>% filter(grepl("^Bambu", TXNAME))
  }
  
  # Select only significant + high LFC for labeling
  select_labels <- res_annot$display_id[!is.na(res_annot$padj) &
                                      res_annot$padj < padj_cutoff &
                                      abs(res_annot$log2FoldChange) >= lfc_cutoff]
  
  # ---- Step 2: Volcano plot ----
  volcano <- EnhancedVolcano(res_annot,
                             lab = res_annot$display_id,
                             selectLab = select_labels,
                             x = "log2FoldChange",
                             y = "padj",
                             pCutoff = padj_cutoff,
                             FCcutoff = lfc_cutoff,
                             pointSize = 2,
                             labSize = 3,
                             drawConnectors = TRUE,
                             boxedLabels = TRUE,
                             
                             widthConnectors = 0.5,
                             title = paste0("Volcano plot: ", prefix),
                             subtitle = "Novel transcripts only",
                             caption = paste0("n = ", nrow(res_annot)),
                             colAlpha = 1,
                             max.overlaps = 20)
  
  
  ##modified
  # ---- Step 2: Volcano plot ----
  # Define custom colors
  # keyvals <- ifelse(
  #   res_annot$padj < padj_cutoff & res_annot$log2FoldChange > lfc_cutoff, "darkred",
  #   ifelse(res_annot$padj < padj_cutoff & res_annot$log2FoldChange < -lfc_cutoff, "darkgreen", "gray50")
  # )
  # names(keyvals)[keyvals == "darkred"] <- "Upregulated"
  # names(keyvals)[keyvals == "darkgreen"] <- "Downregulated"
  # names(keyvals)[keyvals == "gray50"] <- "Not Significant"
  
  # Compute maxima for positioning
  max_x <- max(res_annot$log2FoldChange, na.rm = TRUE)
  min_x <- min(res_annot$log2FoldChange, na.rm = TRUE)
  max_y <- max(-log10(res_annot$padj), na.rm = TRUE)
  
  # Add a little padding above the tallest point
  label_y <- max_y + 0.5
  
  res_annot <- res_annot %>%
    mutate(sig_status = case_when(
    padj < padj_cutoff & log2FoldChange >= lfc_cutoff ~ "Upregulated",
    padj < padj_cutoff & log2FoldChange <= -lfc_cutoff ~ "Downregulated",
    TRUE ~ "Not Significant"
  ))

# Map categories to colors
keyvals <- c("Upregulated" = "darkred", 
             "Downregulated" = "darkgreen", 
             "Not Significant" = "gray50")

# Expand to vector matching rows
colCustom <- keyvals[res_annot$sig_status]

  up_count <- sum(res_annot$padj < padj_cutoff & res_annot$log2FoldChange >= lfc_cutoff, na.rm = TRUE)
  down_count <- sum(res_annot$padj < padj_cutoff & res_annot$log2FoldChange <= -lfc_cutoff, na.rm = TRUE)

  volcano <- EnhancedVolcano(
    res_annot,
    lab = res_annot$display_id,
    selectLab = select_labels,
    x = "log2FoldChange",
    y = "padj",
    pCutoff = padj_cutoff,
    FCcutoff = lfc_cutoff,
    pointSize = 2,
    labSize = 3,
    drawConnectors = TRUE,
    boxedLabels = TRUE,
    widthConnectors = 0.5,
    title = paste0("Volcano plot: ", prefix),
    subtitle = "Novel transcripts only",
    caption = paste0("n = ", nrow(res_annot),
                     " | Thresholds: padj < ", padj_cutoff,
                     ", |log2FC| ≥ ", lfc_cutoff),
    colCustom = colCustom,
    legendLabels = c("Not Significant", "Upregulated", "Downregulated"),
    legendPosition = "top",
    colAlpha = 1,
    max.overlaps = 20
  ) 
  y_lim <- ggplot_build(volcano)$layout$panel_params[[1]]$y.range[2]
  
  volcano <- volcano +
    geom_text(
      aes(x = max(res_annot$log2FoldChange, na.rm = TRUE) * 0.9,
          #y = max(-log10(res_annot$padj), na.rm = TRUE) * 0.9,
          y= y_lim * 0.95,
          label = paste("Up:", up_count)),
      color = "darkred", inherit.aes = FALSE
    ) +
    geom_text(
      aes(x = min(res_annot$log2FoldChange, na.rm = TRUE) * 0.9,
          #y = max(-log10(res_annot$padj), na.rm = TRUE) * 0.9,
          y= y_lim * 0.95,
          label = paste("Down:", down_count)),
      color = "darkgreen", inherit.aes = FALSE
    )

  
  
  
  # ---- Step 3: Heatmap ----
  heatmap <- NULL
  top_tx <- res_annot %>%
    filter(padj < 0.05) %>%
    filter(!is.na(padj)) %>%
    arrange(padj) %>%
    slice_head(n = top_n) %>%
    pull(TXNAME)
  
   if (length(top_tx) > 1) {
      mat <- SummarizedExperiment::assay(vsd)[top_tx, , drop = FALSE]
      
      rownames(mat) <- res_annot$display_id[match(rownames(mat), res_annot$TXNAME)]
      mat <- mat - rowMeans(mat)
      heatmap <- pheatmap(mat,
                          show_rownames = TRUE,
                          cluster_cols = F,
                          breaks = heatmap_breaks,
                          main = paste0("Top ", top_n, " transcripts: ", prefix))
    }
  
  return(list(
    annotated = res_annot,
    volcano = volcano,
    heatmap = heatmap
  ))
}

```


```{r fig.height=7, fig.width=7}
# Volcano + heatmap + annotated table
res_il6 <- annotate_and_plot(plots_il6$results, 
                             gene_annot_df, 
                             out_il6$vsd, "IL6",
                             heatmap_breaks =  seq(-2, 2, length.out = 101),
                             novel_only = TRUE)

res_control <- annotate_and_plot(plots_control$results, 
                             gene_annot_df, 
                             out_control$vsd, "Control", 
                             heatmap_breaks =  seq(-2, 2, length.out = 101),
                             novel_only = TRUE)

res_drna <- annotate_and_plot(plots_drna$results, 
                              gene_annot_df, 
                              out_drna$vsd,
                              "dRNA",
                              heatmap_breaks = seq(-0.5, 0.5, length.out = 101),
                              novel_only = TRUE)

res_cdna <- annotate_and_plot(plots_cdna$results, 
                              #out_cdna$res_shr,
                              gene_annot_df, 
                              out_cdna$vsd,
                              "cDNA", 
                              heatmap_breaks =  seq(-0.5, 0.5, length.out = 101),
                              novel_only = TRUE)

res_cdna$heatmap %>% ggplotify::as.ggplot()
ggsave("DiffExpHeatmap_IL6vsControl_cDNA.svg", width = 8, height = 8, units = "in", dpi = 300,bg = "white")

res_control$heatmap %>% ggplotify::as.ggplot()
ggsave("DiffExpHeatmap_dRNAvscDNA_Control.svg", width = 8, height = 8, units = "in", dpi = 300,bg = "white")

res_il6$heatmap %>% ggplotify::as.ggplot()
ggsave("DiffExpHeatmap_dRNAvscDNA_IL6.svg", width = 8, height = 8, units = "in", dpi = 300,bg = "white")

res_drna$heatmap %>% ggplotify::as.ggplot()
ggsave("DiffExpHeatmap_IL6vsControl_dRNA.svg", width = 8, height = 8, units = "in", dpi = 300,bg = "white")

res_control$volcano
ggsave("DiffExpVolcano_dRNAvscDNA_Control.svg", width = 8, height = 8, units = "in", dpi = 300)

res_il6$volcano
ggsave("DiffExpVolcano_dRNAvscDNA_IL6.svg", width = 8, height = 8, units = "in", dpi = 300)

res_cdna$volcano
ggsave("DiffExpVolcano_IL6vsControl_cDNA.svg", width = 8, height = 8, units = "in", dpi = 300)

res_drna$volcano
ggsave("DiffExpVolcano_IL6vsControl_dRNA.svg", width = 8, height = 8, units = "in", dpi = 300)


```

```{r upset}
library(tidyverse)
library(UpSetR)
library(ggvenn)

# Function to compute expressed novel transcripts overlaps
make_expression_overlap <- function(se, 
                                    group_var1 = "method", 
                                    group_var2 = "condition",
                                    min_counts = 5, 
                                    min_reps = 2,
                                    probable_novel_genes = NULL,
                                    plot_type = c("upset", "venn"), 
                                    novel_only=TRUE) {
  plot_type <- match.arg(plot_type)
  
  cd <- as.data.frame(SummarizedExperiment::colData(se))
  counts <- SummarizedExperiment::assay(se)
  rd <- as.data.frame(SummarizedExperiment::rowData(se))
  
  # ---- Always filter out dodgy geneids ----
  rd <- rd %>%
    filter((GENEID %in% probable_novel_genes) | str_detect(GENEID, "^ENSG"))
  
  # ---- Restrict to novel transcripts ----
  if (novel_only) {
    rd <- rd %>%
      filter(novelTranscript == TRUE |
               str_detect(TXNAME, "^Bambu"))
  }

  
  expressed_sets <- list()
  
  groups <- unique(cd %>% select(all_of(c(group_var1, group_var2))))
  
  for (i in seq_len(nrow(groups))) {
    grp <- groups[i, ]
    grp_name <- paste(grp[[group_var1]], grp[[group_var2]], sep = " ")
    
    grp_samples <- rownames(cd %>% filter(!!sym(group_var1) == grp[[group_var1]],
                                          !!sym(group_var2) == grp[[group_var2]]))
    grp_counts <- counts[, grp_samples, drop = FALSE]
    
    keep <- rowSums(grp_counts >= min_counts) >= min_reps
    expressed <- rownames(se)[keep]
    
    expressed_novel <- expressed[expressed %in% rd$TXNAME]
    expressed_sets[[grp_name]] <- expressed_novel
  }
  
  # ---- Plot ----
  if (plot_type == "upset") {
    upset_data <- fromList(expressed_sets)
    p <- UpSetR::upset(upset_data, order.by = "freq",
               #main.bar.color = "steelblue", sets.bar.color = "grey40",
               mainbar.y.label = "Shared expressed novel transcripts",
               sets.x.label = "Detected novel transcripts")
  } else {
    p <- ggvenn(expressed_sets,
                fill_color = c("red", "blue", "green", "orange"),
                stroke_size = 0.5, set_name_size = 4)
  }
  
  return(list(
    expressed_sets = expressed_sets,
    plot = p
  ))
}

```


```{r de_overlaps}
summarise_de_overlaps <- function(result_list, 
                                  result_names,
                                  comparison_type = c("IL6vsControl", "dRNAvscDNA"),
                                  alpha = 0.05, 
                                  lfc_threshold = 1,
                                  novel_only = TRUE,
                                  venn_if_small = TRUE) {
  comparison_type <- match.arg(comparison_type)
  
  sig_sets <- list()
  summary_df <- data.frame()
  
  for (i in seq_along(result_list)) {
    df <- result_list[[i]]
    nm <- result_names[[i]]
    
    df <- df %>% filter(!is.na(padj))
    
    if (novel_only) {
      df <- df %>% filter(str_detect(TXNAME, "^Bambu"))
    }
    
    # Interpret direction depending on comparison type
    if (comparison_type == "IL6vsControl") {
      up_label <- paste0(nm, " IL6") 
      down_label <- paste0(nm, " Control") 
      
      sig_up <- df %>% filter(padj < alpha, log2FoldChange >= lfc_threshold) %>% pull(TXNAME)
      sig_down <- df %>% filter(padj < alpha, log2FoldChange <= -lfc_threshold) %>% pull(TXNAME)
      
      sig_sets[[up_label]] <- unique(sig_up)
      sig_sets[[down_label]] <- unique(sig_down)
      
    } else if (comparison_type == "dRNAvscDNA") {
      up_label <- paste0(nm, " dRNA") 
      down_label <- paste0(nm, " cDNA") 
      
      sig_up <- df %>% filter(padj < alpha, log2FoldChange >= lfc_threshold) %>% pull(TXNAME)
      sig_down <- df %>% filter(padj < alpha, log2FoldChange <= -lfc_threshold) %>% pull(TXNAME)
      
      sig_sets[[up_label]] <- unique(sig_up)
      sig_sets[[down_label]] <- unique(sig_down)
    }
  }
  
  # Build summary counts
  all_tx <- unique(unlist(sig_sets))
  summary_df <- data.frame(transcript_id = all_tx)
  
  for (nm in names(sig_sets)) {
    summary_df[[nm]] <- summary_df$transcript_id %in% sig_sets[[nm]]
  }
  
  # Choose plot type
  if (length(sig_sets) <= 4 && venn_if_small) {
    p <- ggvenn(sig_sets,
                fill_color = c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
                               "#FF7F00", "#A65628", "#F781BF", "#999999")[1:length(sig_sets)],
                stroke_size = 0.5, set_name_size = 3, text_size = 3)
  } else {
    p <- upset(fromList(sig_sets),
               order.by = "freq",
               mainbar.y.label = "Shared novel transcripts",
               sets.x.label = "Novel transcripts per set")
  }
  
  return(list(
    sig_sets = sig_sets,
    summary = summary_df,
    plot = p
  ))
}

```


```{r dte_overlaps}
# 1a. Novel expression overlaps
expr_overlap <- make_expression_overlap(
  se.bambu,
  probable_novel_genes = probable_novel_genes,
  min_counts = 5, min_reps = 2,
  plot_type = "upset"
)

expr_overlap$plot

svg("novel_transcripts_upset1.svg", width = 8, height = 6)  # pixels and dpi
expr_overlap$plot
dev.off()



# 1b. Novel expression overlaps
all_expr_overlap <- make_expression_overlap(
  se.bambu,
  probable_novel_genes = probable_novel_genes,
  min_counts = 5, min_reps = 2,
  plot_type = "upset",
  novel_only = FALSE
  
)

```


```{r fig.height=8, fig.width=8}
# 2. DE overlaps
# For IL6 vs Control (within method comparisons)

de_overlap_il6 <- summarise_de_overlaps(
  #list(plots_cdna$results, plots_drna$results),
  list(res_cdna$annotated, res_drna$annotated),
  c("cDNA", "dRNA"),
  comparison_type = "IL6vsControl",
  alpha = 0.05, lfc_threshold = 1, novel_only = TRUE, FALSE
)

de_overlap_il6$plot


svg("DiffExp_IL6vsControl.svg", width = 8, height = 6)  
de_overlap_il6$plot
dev.off()

# For dRNA vs cDNA (within condition comparisons)
de_overlap_method <- summarise_de_overlaps(
  #list(plots_control$results, plots_il6$results),
  list(res_control$annotated, res_il6$annotated),
  c("Control", "IL6"),
  comparison_type = "dRNAvscDNA",
  alpha = 0.05, lfc_threshold = 1, novel_only = TRUE, FALSE
)
svg("DiffExp_dRNAvscDNA.svg", width = 8, height = 6)  
de_overlap_method$plot
dev.off()

de_overlap_method$plot

ggsave(file.path(plots_dir, "DiffExp_dRNAvscDNA.svg"), height = 8, width = 6, units = "in", dpi = 300, bg="white")
```


```{r}
setA <- expr_overlap$expressed_sets$dRNA_Control
setB <- expr_overlap$expressed_sets$dRNA_IL6
setC <- expr_overlap$expressed_sets$cDNA_Control
setD <- expr_overlap$expressed_sets$cDNA_IL6

unique_dRNA <- base::setdiff(base::intersect(setA, setB), base::union(setC, setD))
unique_cDNA <- base::setdiff(base::intersect(setC, setD), base::union(setA, setB))

unique_Control <- base::setdiff(base::intersect(setC, setA), base::union(setD, setB))
unique_IL6 <- base::setdiff(base::intersect(setB, setD), base::union(setA, setC))

test1 <- gene_annot %>%
  group_by(GENEID, seqnames, strand) %>%
  summarise(width =sum(width), n_exons=n(), start=min(start), end = max(end))
  
interesting_novel_transcripts <- data.frame(
  TXID = c(unique_dRNA, unique_cDNA, unique_Control, unique_IL6),
  set = c(rep("unique_dRNA", length(unique_dRNA)), rep("unique_cDNA", length(unique_cDNA)), rep("unique_Control", length(unique_Control)), rep("unique_IL6", length(unique_IL6)))
  
)  %>% left_join(tx_annot %>% select(TXID, GENEID) %>% distinct()) %>%
  left_join(gene_annot_df, by=c("GENEID"="gene_id")) %>%
  left_join(test1)
  

interesting_novel_genes <- interesting_novel_transcripts %>%
  filter(GENEID %>% str_detect("^Bambu"))

interesting_novel_transcripts %>% group_by(set) %>% summarise(n())

# Convert to GRanges
query <- GRanges(
  seqnames = interesting_novel_genes$seqnames,
  ranges = IRanges(start = interesting_novel_genes$start, end = interesting_novel_genes$end),
  strand = interesting_novel_genes$strand
)

gtf_granges<- import(gtf_file)
granges_genes <- gtf_granges[gtf_granges$type == "gene"]
hits <- findOverlaps(query, granges_genes)
hits_annot <- granges_genes[subjectHits(hits)]

data.frame(
  query_chr = seqnames(query)[queryHits(hits)],
  query_start = start(query)[queryHits(hits)],
  query_end = end(query)[queryHits(hits)],
  query_strand = strand(query)[queryHits(hits)],
  gene_id = hits_annot$gene_id,
  gene_name = hits_annot$gene_name,
  gene_biotype = hits_annot$gene_biotype
)

```

```{r}
library(clusterProfiler)
library(org.Hs.eg.db)
library(msigdbr)
library(ReactomePA)
library(DOSE)
library(ggplot2)

run_enrichment <- function(gene_list, background = NULL, species = "Homo sapiens", prefix = "test", is_entrez = TRUE) {
  # Convert ENSG IDs to ENTREZ for clusterProfiler
  if (!is_entrez) {
    gene_entrez <- gene_list %>% mapIds(x = edb,
                                        keytype = "GENEID",
                                        column = "ENTREZID") %>%
      na.omit()
  } else {gene_entrez <- gene_list}
  
  
  if (!is.null(background)) {
    if (!is_entrez) {
      bg_entrez <- background %>% mapIds(x = edb,
                                        keytype = "GENEID",
                                        column = "ENTREZID") %>%
      na.omit()
  } else {bg_entrez <- background}
    
    } else {
    bg_entrez <- NULL
  
  }
  results <- list()
  
  ## Hallmark
  hallmark <- msigdbr(species = species, category = "H") %>% dplyr::select(gs_name, entrez_gene)
  results$hallmark <- enricher(gene_entrez, TERM2GENE = hallmark, universe = bg_entrez)

  ## KEGG
  results$kegg <- enrichKEGG(gene = gene_entrez, universe = bg_entrez, organism = "hsa")

  ## Reactome
  results$reactome <- enrichPathway(gene = gene_entrez, universe = bg_entrez, organism = "human")

  ## GO BP
  results$go_bp <- enrichGO(gene = gene_entrez, OrgDb = org.Hs.eg.db, ont = "BP", universe = bg_entrez)

  ## Disease ontology
  results$disease <- enrichDO(gene = gene_entrez, universe = bg_entrez)

  ## C2 curated sets
  c2 <- msigdbr(species = species, category = "C2") %>% dplyr::select(gs_name, entrez_gene)
  results$c2 <- enricher(gene_entrez, TERM2GENE = c2, universe = bg_entrez)

  ## Custom IL6/JAK/STAT pathway (can be built from msigdbr or your own list)
  jak_il6 <- msigdbr(species = species, category = "H") %>%
    dplyr::filter(grepl("IL6_JAK_STAT3", gs_name)) %>%
    dplyr::select(gs_name, entrez_gene)
  results$jakstat <- enricher(gene_entrez, TERM2GENE = jak_il6, universe = bg_entrez)

  ## Add plots
  plots <- lapply(results, function(res) {
    if (!is.null(res) && nrow(as.data.frame(res)) > 0) {
      return(dotplot(res, showCategory = 15, title = paste(prefix, deparse(substitute(res)))))
    } else {
      return(NULL)
    }
  })

  return(list(results = results, plots = plots))
}

```

```{r}
background <- rd %>%
  filter(TXNAME %in% c(all_expr_overlap$expressed_sets$dRNA_Control, all_expr_overlap$expressed_sets$dRNA_IL6)) %>%
  pull(GENEID) %>% tools::file_path_sans_ext()  %>% mapIds(x = edb,
                                                           keytype = "GENEID",
                                                           column = "ENTREZID") %>%
  na.omit() %>% unique()

geneset <- interesting_novel_transcripts %>%
  filter(set == "unique_dRNA") %>%
  filter(GENEID %>% str_detect("^ENSG")) %>%
    pull(GENEID) %>% tools::file_path_sans_ext()  %>% mapIds(x = edb,
                                                           keytype = "GENEID",
                                                           column = "ENTREZID") %>%
  na.omit() %>% unique()


geneset <- interesting_novel_transcripts %>%
  filter(set == "unique_cDNA") %>%
  filter(GENEID %>% str_detect("^ENSG")) %>%
    pull(GENEID) %>% tools::file_path_sans_ext()  %>% mapIds(x = edb,
                                                           keytype = "GENEID",
                                                           column = "ENTREZID") %>%
  na.omit() %>% unique()

dRNA_novel_gene_enrichment <- run_enrichment(gene_list = geneset, background = background, prefix = "dRNA", is_entrez = T)

dRNA_novel_gene_enrichment$plots

cDNA_novel_gene_enrichment <- run_enrichment(gene_list = geneset, background = background, prefix = "cDNA", is_entrez = T)

cDNA_novel_gene_enrichment$plots

```


```{r mm_drivers}

library(hgu133plus2.db)
library(UpSetR)


maura_genes <- fread("maura_genes.txt") %>% pull() %>%
  mapIds(x = EnsDb.Hsapiens.v86::EnsDb.Hsapiens.v86,
         keytype = "GENENAME",
         column = "GENEID") %>%
  na.omit() %>% 
    unique()
  
walker_genes <- fread("walkers_genes.txt") %>%
  pull()  %>%
  str_replace("ORF", "orf") %>%
  mapIds(x = EnsDb.Hsapiens.v86::EnsDb.Hsapiens.v86,
         keytype = "GENENAME",
         column = "GENEID") %>%
  na.omit() %>% 
    unique()
  
  
# Map probes → gene ids
uams70_table <- fread("uams70.txt")  
uams70_table <- uams70_table %>%
  mutate(gene_id = mapIds(
  hgu133plus2.db,
  keys = Probe,
  column = "ENSEMBL",
  keytype = "PROBEID",
  multiVals = "first" # if multiple genes, take first (you can adjust)
)) %>%
  mutate(hgnc_symbol = mapIds(
  hgu133plus2.db,
  keys = Probe,
  column = "SYMBOL",
  keytype = "PROBEID",
  multiVals = "first" # if multiple genes, take first (you can adjust)
)) %>%
  mutate(gene_id = ifelse(str_detect(Probe, "227547_at"), "ENSG00000215529", gene_id)) %>%
  mutate(hgnc_symbol = ifelse(str_detect(Probe, "227547_at"), "EFCAB8", hgnc_symbol))
  
emc92_table <- fread("emc92.txt")
# Map probes → gene ids
emc92_table <- emc92_table %>%
  mutate(gene_id = mapIds(
  hgu133plus2.db,
  keys = Probe,
  column = "ENSEMBL",
  keytype = "PROBEID",
  multiVals = "first" # if multiple genes, take first (you can adjust)
)) %>%
  mutate(hgnc_symbol = mapIds(
  hgu133plus2.db,
  keys = Probe,
  column = "SYMBOL",
  keytype = "PROBEID",
  multiVals = "first" # if multiple genes, take first (you can adjust)
)) %>%
  mutate(gene_id = ifelse(str_detect(Probe, "M97935_MA_at"), "ENSG00000115415", gene_id)) %>%
  mutate(hgnc_symbol = ifelse(str_detect(Probe, "M97935_MA_at"), "STAT1", hgnc_symbol))



check_mm_overlap <- function(gene_list, name="Gene_List") {

  sets <- list(
    Maura = maura_genes,
    Walker = walker_genes,
    EMC92 = emc92_table$gene_id,
    UAMS70 = uams70_table$gene_id
  )

  # Compute overlaps
  summary <- lapply(sets, function(s) {
    overlap <- intersect(gene_list, s)
    list(
      n_set = length(s),
      n_overlap = length(overlap),
      overlap_genes = overlap
    )
  })

  # Convert to data.frame
  df <- do.call(rbind, lapply(names(summary), function(n) {
    data.frame(
      set = n,
      n_set = summary[[n]]$n_set,
      n_overlap = summary[[n]]$n_overlap,
      overlap_genes = paste(summary[[n]]$overlap_genes, collapse = ",")
    )
  }))
  
  
  sets[[name]] <- gene_list 

  # Optional visualization
  list(summary = df,
       upset = UpSetR::upset(fromList(sets), nsets = 5))
}


library(ComplexUpset)

check_mm_overlap <- function(gene_list, name) {
  
 sets <- list(
    Maura = maura_genes,
    Walker = walker_genes,
    EMC92 = emc92_table$gene_id,
    UAMS70 = uams70_table$gene_id
  )
 
 sets[[name]] <- gene_list

  # ---- Build a binary membership matrix ----
  all_genes <- unique(unlist(sets))
  df <- data.frame(gene = all_genes)
  for (nm in names(sets)) {
    df[[nm]] <- df$gene %in% sets[[nm]]
  }

  # ---- Overlap summary (your list vs each MM set) ----
  summary <- do.call(rbind, lapply(names(sets)[-1], function(n) {
    overlap <- intersect(gene_list, sets[[n]])
    data.frame(
      set = n,
      n_set = length(sets[[n]]),
      n_overlap = length(overlap),
      overlap_genes = paste(overlap, collapse = ",")
    )
  }))

  # ---- ComplexUpset plot ----
  upset_plot <- ComplexUpset::upset(
    df,
    intersect = names(sets),
    min_degree=2,
    intersections=list(
        c('Comedy', 'Romance'),
        c('Romance', 'Drama')
    )
    
  
    # base_annotations = list(
    #   'Intersection size' = intersection_size(bar_number = TRUE)
    # )
  ) + ggtitle(paste("Overlap of", name, "with MM sets", sep = " "))

  return(list(summary = summary, plot = upset_plot))
}



geneset <- interesting_novel_transcripts %>%
  filter(set == "unique_dRNA") %>%
  filter(GENEID %>% str_detect("^ENSG")) %>%
    pull(GENEID) %>% tools::file_path_sans_ext()


check_mm_overlap(gene_list = geneset, name= "Unique dRNA novel isoforms")


geneset <- interesting_novel_transcripts %>%
  filter(set == "unique_cDNA") %>%
  filter(GENEID %>% str_detect("^ENSG")) %>%
    pull(GENEID) %>% tools::file_path_sans_ext()


check_mm_overlap(gene_list = geneset, name= "Unique cDNA novel isoforms")
```

```{r transcript_plot}

#rowData(se.bambu) %>% as.data.frame() %>% View()
#plotBambu(se.bambu, type = "annotation", gene_id = "ENSG00000057657.17")


PRDM1_exons <- bambu_gtf %>% as.data.frame() %>%
  filter(gene_id %in% "ENSG00000057657.17", 
         type == "exon") %>%
  mutate(gene_name="PRDM1") %>%
  left_join(annotation_table %>%
  filter(gene_id %in% "ENSG00000057657.17") %>% 
  select(transcript_id, transcript_type) %>% distinct() %>% 
  drop_na()) %>%
  
  
  mutate(transcript_name= paste(gene_name,
                                tools::file_path_sans_ext(transcript_id), sep="_")) %>%
  mutate(transcript_type = ifelse(is.na(transcript_type), "Unknown", str_to_title(str_replace_all(transcript_type, "_", " "))))

PRDM1_exons %>%
    ggplot(aes(
        xstart = start,
        xend = end,
        y = transcript_name
    )) +
    geom_range(
        aes(fill = transcript_type)
    ) +
    geom_intron(
        data = to_intron(PRDM1_exons, "transcript_name"),
        aes(strand = strand)
    )





PRDM1_rescaled <- shorten_gaps(
  PRDM1_exons, 
  to_intron(PRDM1_exons, "transcript_name"), 
  group_var = "transcript_name"
  )

(PRDM1_rescaled %>%
    dplyr::filter(type == "exon") %>%
    ggplot(aes(
        xstart = start,
        xend = end,
        y = transcript_name
    )) +
    geom_range(
      aes(fill = transcript_type)
    ) +
    geom_intron(
        data = PRDM1_rescaled %>% dplyr::filter(type == "intron"), 
        arrow.min.intron.length = 200
    ) + theme_minimal() ) %>% ggpar(legend.title = "Biotype", xlab="Length (bp)", ylab="", font.family = "sans", font.tickslab = c(10, "black"))
```
